name: ExampleCI
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Example Compile
        shell: bash
        run: |
          cd example
          make clean
          make
          ./test
