name: Agile_Upgrade
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Example Compile
        shell: bash
        run: |
          gcc -v
          cd example
          make
